apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-demo-canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary-demo
      version: canary
  template:
    metadata:
      labels:
        app: canary-demo
        version: canary
    spec:
      containers:
      - name: app
        image: coderuner/canary-demo:release-0.7
        ports:
        - containerPort: 8080
        imagePullPolicy: Always



