apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: canary-demo
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`localhost`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: canary-demo-weighted
      kind: TraefikService
