apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: canary-demo-weighted
spec:
  weighted:
    services:
      - name: canary-demo-stable
        port: 80
        weight: 80
      - name: canary-demo-canary
        port: 80
        weight: 20
